### ISSUE TITLE
macOS Catalyst canvas glitches on 'clear()'

### ISSUE THREAD

**Issue by VihlayewAlex** [Harley-xk/MaLiang#70] opened 2020-02-17 13:59 UTC
Hi! 
I built MaLiang Example for Mac Catalyst, with no changes except for the "Mac" checkmark in Xcode project settings.
When drawing curves and hitting clear button I get glitches of previous drawings on the canvas.
How can it be fixes?

I have issues on macOS 10.15.3 and all other OS versions

Attached example screenshot:
![Screenshot 2020-02-17 at 15 52 01](https://user-images.githubusercontent.com/22377058/74659859-c11f7100-519d-11ea-8368-e21ec6a6e6e8.png)

Also attached an archive with video illustrating the issue:
[Screen Recording 2020-02-17 at 15.48.25.mov.zip](https://github.com/Harley-xk/MaLiang/files/4214104/Screen.Recording.2020-02-17.at.15.48.25.mov.zip)

**Comment by Harley-xk** [comment] 2020-02-19 08:05
Yes, it seems the newly created empty texture was polluted, now fixed in 2.6.4

**Comment by ERbittuu** [comment] 2020-03-01 12:24
Same issue in ios.
cavan not clear when clear button pressed.

**Comment by stanislau-king** [comment] 2020-03-22 16:40
The problem is urgent in ios! Have a quick fix?

**Comment by Harley-xk** [comment] 2020-03-25 06:36
@ERbittuu @stanislau-king thanks a lot, this problem is now fixed in 2.7.0

**Comment by stanislau-king** [comment] 2020-03-25 06:45
> @ERbittuu @stanislau-king thanks a lot, this problem is now fixed in 2.7.0

Great news! Thank you!

**Comment by stanislau-king** [comment] 2020-03-25 17:05
> @ERbittuu @stanislau-king thanks a lot, this problem is now fixed in 2.7.0

Hi,

New version 2.7.0 is not available. (

**Closed** 2020-03-26 00:19 UTC
